"""Parameter sweep / 区间参数 expansion.

Only uniform simplex grid sampling is supported (kind:'simplex'): all lattice
points on the (n-1)-simplex at resolution T, generated by
nimplex.simplex_grid_fractional_py(n, T).  Use this for list[float] params
whose values must sum to 1 (e.g. weights).

Optional per-component bounds (`min`, `max` arrays of length n) filter out
lattice points that violate any component bound.  Defaults are 0 / 1.

Each child job consumes exactly one resolved dict via the existing runner
path, so this module has zero rasterio / FastAPI dependencies and is fully
unit-testable in isolation.
"""
from __future__ import annotations

import copy
import itertools
import math
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..algorithms.registry import AlgorithmInfo


MAX_SWEEP_SAMPLES = 200

# Floating-point slack when comparing nimplex k/T values against bounds.
_BOUND_TOL = 1e-9

# nimplex native extension lives in backend/vendor/nimplex.so
_VENDOR_DIR = Path(__file__).parent.parent.parent / "vendor"


def _nimplex():
    """Lazy-import nimplex from vendor/, raising ImportError with a clear message."""
    vendor = str(_VENDOR_DIR)
    if vendor not in sys.path:
        sys.path.insert(0, vendor)
    try:
        import nimplex as _nx  # noqa: PLC0415
        return _nx
    except ImportError as e:
        raise ImportError(
            f"nimplex.so not found in {_VENDOR_DIR}. "
            "Build it from https://github.com/amkrajewski/nimplex "
            "and copy nimplex.so into backend/vendor/."
        ) from e


@dataclass(frozen=True)
class SimplexSpec:
    """Uniform grid on the (n-1)-simplex via nimplex, with optional bounds.

    n_components: dimensionality (inferred from len(base_params[param_name])).
    n_divisions:  T — step = 1/T; unfiltered sample count = C(n + T - 1, T).
    min_bounds:   optional per-component lower bound (defaults to 0).
    max_bounds:   optional per-component upper bound (defaults to 1).
    When either bound is set, lattice points with any component outside its
    [min, max] interval are dropped.
    """
    n_components: int
    n_divisions: int
    min_bounds: tuple[float, ...] | None = None
    max_bounds: tuple[float, ...] | None = None


ParamRangeSpec = SimplexSpec


# ----------------------------------------------------------------------------
# Public API
# ----------------------------------------------------------------------------


def parse_param_ranges(
    raw: dict[str, Any],
    algo_info: AlgorithmInfo,
    base_params: dict[str, Any],
) -> dict[str, ParamRangeSpec]:
    """Validate and normalize a raw `param_ranges` payload into typed specs.

    Raises ValueError with a human-readable message for any validation failure.
    The API layer turns this into HTTP 400.
    """
    if not isinstance(raw, dict):
        raise ValueError("param_ranges must be an object")

    by_name = {p.name: p for p in algo_info.params}
    out: dict[str, ParamRangeSpec] = {}

    for name, spec in raw.items():
        if name not in by_name:
            raise ValueError(f"Unknown param '{name}' in param_ranges")
        pspec = by_name[name]
        if not pspec.sweepable:
            raise ValueError(f"Param '{name}' is not sweepable")
        if not isinstance(spec, dict) or "kind" not in spec:
            raise ValueError(f"param_ranges['{name}'] must be an object with a 'kind' field")

        kind = spec["kind"]
        if kind == "simplex":
            if pspec.type != "list[float]":
                raise ValueError(
                    f"Param '{name}' is {pspec.type!r}; only list[float] accepts kind='simplex'"
                )
            out[name] = _parse_simplex(spec, base_params.get(name), name)
        else:
            raise ValueError(
                f"param_ranges['{name}'].kind must be 'simplex'"
            )

    return out


def sweep_size(ranges: dict[str, ParamRangeSpec]) -> int:
    """Number of samples in the Cartesian product across all axes.

    When a SimplexSpec has bounds set, the grid is materialized and filtered
    to get the exact count; otherwise the closed-form binomial is used.
    """
    total = 1
    for spec in ranges.values():
        if isinstance(spec, SimplexSpec):
            total *= _simplex_size(spec)
    return total


def expand_ranges(
    base_params: dict[str, Any],
    ranges: dict[str, ParamRangeSpec],
    algo_info: AlgorithmInfo,
) -> list[tuple[dict[str, Any], str]]:
    """Expand sweep specs into a list of (resolved_params, sample_label).

    Axes are iterated in `algo_info.params` declaration order. This makes
    sample_index stable across submissions of the same shape.

    Raises ValueError if any simplex axis has bounds that eliminate every
    lattice point.
    """
    # 1. Collect axes in declaration order.
    axes: list[_Axis] = []
    for pspec in algo_info.params:
        if pspec.name not in ranges:
            continue
        spec = ranges[pspec.name]
        if isinstance(spec, SimplexSpec):
            samples = _simplex_samples(spec)
            if not samples:
                raise ValueError(
                    f"param_ranges['{pspec.name}']: bounds eliminate all "
                    f"{_simplex_unfiltered_size(spec)} lattice points"
                )
            axes.append(_Axis(param=pspec.name, samples=samples))

    if not axes:
        # Degenerate: no sweep declared. Return the single base case.
        return [(copy.deepcopy(base_params), "")]

    # 2. Cartesian product across all axes.
    out: list[tuple[dict[str, Any], str]] = []
    for combo in itertools.product(*(a.samples for a in axes)):
        resolved = copy.deepcopy(base_params)
        label_bits: list[str] = []
        for axis, value in zip(axes, combo):
            resolved[axis.param] = list(value)
            label_bits.append(
                f"{axis.param}=[{','.join(_fmt(v) for v in value)}]"
            )
        out.append((resolved, "_".join(label_bits)))

    return out


def format_combo_suffix(label_bits: list[str]) -> str:
    """Join label fragments with '_' and truncate ultra-long labels."""
    s = "_".join(label_bits)
    if len(s) > 80:
        s = s[:38] + "..." + s[-38:]
    return s


# ----------------------------------------------------------------------------
# Internals
# ----------------------------------------------------------------------------


@dataclass(frozen=True)
class _Axis:
    param: str
    samples: tuple[Any, ...]


def _parse_simplex(spec: dict, base_value: Any, name: str) -> SimplexSpec:
    if not isinstance(base_value, list) or len(base_value) < 2:
        raise ValueError(
            f"params['{name}'] must be a list of length >= 2 for kind='simplex'; "
            f"got {type(base_value).__name__ if not isinstance(base_value, list) else f'len={len(base_value)}'}"
        )
    raw_nd = spec.get("n_divisions")
    try:
        nd = int(raw_nd)
        if nd != raw_nd:  # catches floats like 4.5
            raise ValueError
    except (TypeError, ValueError):
        raise ValueError(
            f"param_ranges['{name}'].n_divisions must be a positive integer"
        )
    if nd < 1:
        raise ValueError(f"param_ranges['{name}'].n_divisions must be >= 1")

    n = len(base_value)
    min_bounds = _parse_bound_array(spec.get("min"), n, name, "min")
    max_bounds = _parse_bound_array(spec.get("max"), n, name, "max")

    # Per-component ordering and feasibility checks.
    lo = min_bounds if min_bounds is not None else (0.0,) * n
    hi = max_bounds if max_bounds is not None else (1.0,) * n
    for i, (a, b) in enumerate(zip(lo, hi)):
        if a > b + _BOUND_TOL:
            raise ValueError(
                f"param_ranges['{name}']: min[{i}]={a} > max[{i}]={b}"
            )
    if sum(lo) > 1.0 + _BOUND_TOL:
        raise ValueError(
            f"param_ranges['{name}']: sum(min)={sum(lo):g} > 1; no weight vector is feasible"
        )
    if sum(hi) < 1.0 - _BOUND_TOL:
        raise ValueError(
            f"param_ranges['{name}']: sum(max)={sum(hi):g} < 1; no weight vector is feasible"
        )

    return SimplexSpec(
        n_components=n,
        n_divisions=nd,
        min_bounds=min_bounds,
        max_bounds=max_bounds,
    )


def _parse_bound_array(
    raw: Any, n: int, name: str, which: str
) -> tuple[float, ...] | None:
    """Validate an optional `min`/`max` array. Returns None if raw is None."""
    if raw is None:
        return None
    if not isinstance(raw, list):
        raise ValueError(
            f"param_ranges['{name}'].{which} must be a list of {n} floats"
        )
    if len(raw) != n:
        raise ValueError(
            f"param_ranges['{name}'].{which} length {len(raw)} does not match "
            f"params['{name}'] length {n}"
        )
    out: list[float] = []
    for i, v in enumerate(raw):
        if not isinstance(v, (int, float)) or isinstance(v, bool):
            raise ValueError(
                f"param_ranges['{name}'].{which}[{i}] must be a number"
            )
        f = float(v)
        if f < -_BOUND_TOL or f > 1.0 + _BOUND_TOL:
            raise ValueError(
                f"param_ranges['{name}'].{which}[{i}]={f} must lie in [0, 1]"
            )
        out.append(max(0.0, min(1.0, f)))
    return tuple(out)


def _simplex_unfiltered_size(spec: SimplexSpec) -> int:
    """C(n + T - 1, T) — lattice point count before applying bounds."""
    return math.comb(spec.n_components + spec.n_divisions - 1, spec.n_divisions)


def _simplex_size(spec: SimplexSpec) -> int:
    """Exact post-filter sample count. Materializes the grid when bounds are set."""
    if spec.min_bounds is None and spec.max_bounds is None:
        return _simplex_unfiltered_size(spec)
    return len(_simplex_samples(spec))


def _simplex_samples(spec: SimplexSpec) -> tuple[tuple[float, ...], ...]:
    """Generate (and filter) lattice points. Each row sums to 1."""
    nx = _nimplex()
    grid = nx.simplex_grid_fractional_py(spec.n_components, spec.n_divisions)
    rows = (tuple(row) for row in grid)
    if spec.min_bounds is None and spec.max_bounds is None:
        return tuple(rows)
    lo = spec.min_bounds if spec.min_bounds is not None else (0.0,) * spec.n_components
    hi = spec.max_bounds if spec.max_bounds is not None else (1.0,) * spec.n_components
    return tuple(
        row for row in rows
        if all(lo[i] - _BOUND_TOL <= v <= hi[i] + _BOUND_TOL for i, v in enumerate(row))
    )


def _fmt(v: Any) -> str:
    """Compact numeric formatting for labels: '1' not '1.0', '0.25' not '0.250000'."""
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        if v.is_integer():
            return str(int(v))
        return f"{v:g}"
    return str(v)
